/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CommentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CommentsApiTests
    {
        private CommentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CommentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CommentsApi
            //Assert.IsInstanceOfType(typeof(CommentsApi), instance, "instance is a CommentsApi");
        }

        
        /// <summary>
        /// Test CommentsAddComment
        /// </summary>
        [Test]
        public void CommentsAddCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewComment newComment = null;
            //instance.CommentsAddComment(newComment);
            
        }
        
        /// <summary>
        /// Test CommentsGet
        /// </summary>
        [Test]
        public void CommentsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filter = null;
            //string orderby = null;
            //int? top = null;
            //int? skip = null;
            //var response = instance.CommentsGet(filter, orderby, top, skip);
            //Assert.IsInstanceOf<CommentPage> (response, "response is CommentPage");
        }
        
    }

}
