/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrdersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrdersApi
            //Assert.IsInstanceOfType(typeof(OrdersApi), instance, "instance is a OrdersApi");
        }

        
        /// <summary>
        /// Test OrdersAddOrder
        /// </summary>
        [Test]
        public void OrdersAddOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewOrder newOrder = null;
            //var response = instance.OrdersAddOrder(newOrder);
            //Assert.IsInstanceOf<Guid?> (response, "response is Guid?");
        }
        
        /// <summary>
        /// Test OrdersDeleteOrder
        /// </summary>
        [Test]
        public void OrdersDeleteOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.OrdersDeleteOrder(id);
            
        }
        
        /// <summary>
        /// Test OrdersEditOrder
        /// </summary>
        [Test]
        public void OrdersEditOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EditOrder order = null;
            //instance.OrdersEditOrder(order);
            
        }
        
        /// <summary>
        /// Test OrdersGetByID
        /// </summary>
        [Test]
        public void OrdersGetByIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.OrdersGetByID(id);
            //Assert.IsInstanceOf<OrderDetails> (response, "response is OrderDetails");
        }
        
    }

}
