/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProspectsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProspectsApiTests
    {
        private ProspectsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProspectsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProspectsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProspectsApi
            //Assert.IsInstanceOfType(typeof(ProspectsApi), instance, "instance is a ProspectsApi");
        }

        
        /// <summary>
        /// Test ProspectsAddProspect
        /// </summary>
        [Test]
        public void ProspectsAddProspectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewProspect newProspect = null;
            //var response = instance.ProspectsAddProspect(newProspect);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ProspectsDeleteByID
        /// </summary>
        [Test]
        public void ProspectsDeleteByIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.ProspectsDeleteByID(id);
            
        }
        
        /// <summary>
        /// Test ProspectsEditClient
        /// </summary>
        [Test]
        public void ProspectsEditClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EditProspect prospect = null;
            //instance.ProspectsEditClient(prospect);
            
        }
        
        /// <summary>
        /// Test ProspectsGet
        /// </summary>
        [Test]
        public void ProspectsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.ProspectsGet(id);
            //Assert.IsInstanceOf<ProspectDetails> (response, "response is ProspectDetails");
        }
        
        /// <summary>
        /// Test ProspectsGetProspects
        /// </summary>
        [Test]
        public void ProspectsGetProspectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filter = null;
            //string orderby = null;
            //int? top = null;
            //int? skip = null;
            //var response = instance.ProspectsGetProspects(filter, orderby, top, skip);
            //Assert.IsInstanceOf<ProspectListItemPage> (response, "response is ProspectListItemPage");
        }
        
    }

}
