/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EditWebHookSubscription
    /// </summary>
    [DataContract]
    public partial class EditWebHookSubscription :  IEquatable<EditWebHookSubscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditWebHookSubscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EditWebHookSubscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EditWebHookSubscription" /> class.
        /// </summary>
        /// <param name="_Event">_Event (required).</param>
        /// <param name="TargetUrl">TargetUrl (required).</param>
        public EditWebHookSubscription(string _Event = default(string), string TargetUrl = default(string))
        {
            // to ensure "_Event" is required (not null)
            if (_Event == null)
            {
                throw new InvalidDataException("_Event is a required property for EditWebHookSubscription and cannot be null");
            }
            else
            {
                this._Event = _Event;
            }
            // to ensure "TargetUrl" is required (not null)
            if (TargetUrl == null)
            {
                throw new InvalidDataException("TargetUrl is a required property for EditWebHookSubscription and cannot be null");
            }
            else
            {
                this.TargetUrl = TargetUrl;
            }
        }
        
        /// <summary>
        /// Gets or Sets _Event
        /// </summary>
        [DataMember(Name="event", EmitDefaultValue=false)]
        public string _Event { get; set; }

        /// <summary>
        /// Gets or Sets TargetUrl
        /// </summary>
        [DataMember(Name="target_url", EmitDefaultValue=false)]
        public string TargetUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EditWebHookSubscription {\n");
            sb.Append("  _Event: ").Append(_Event).Append("\n");
            sb.Append("  TargetUrl: ").Append(TargetUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EditWebHookSubscription);
        }

        /// <summary>
        /// Returns true if EditWebHookSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of EditWebHookSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EditWebHookSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Event == input._Event ||
                    (this._Event != null &&
                    this._Event.Equals(input._Event))
                ) && 
                (
                    this.TargetUrl == input.TargetUrl ||
                    (this.TargetUrl != null &&
                    this.TargetUrl.Equals(input.TargetUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Event != null)
                    hashCode = hashCode * 59 + this._Event.GetHashCode();
                if (this.TargetUrl != null)
                    hashCode = hashCode * 59 + this.TargetUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
