/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NewWebHookSubscription
    /// </summary>
    [DataContract]
    public partial class NewWebHookSubscription :  IEquatable<NewWebHookSubscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewWebHookSubscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NewWebHookSubscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NewWebHookSubscription" /> class.
        /// </summary>
        /// <param name="_event">_event (required).</param>
        /// <param name="target_url">target_url (required).</param>
        public NewWebHookSubscription(string _event = default(string), string target_url = default(string))
        {
            // to ensure "_event" is required (not null)
            if (_event == null)
            {
                throw new InvalidDataException("_event is a required property for NewWebHookSubscription and cannot be null");
            }
            else
            {
                this._event = _event;
            }
            // to ensure "target_url" is required (not null)
            if (target_url == null)
            {
                throw new InvalidDataException("target_url is a required property for NewWebHookSubscription and cannot be null");
            }
            else
            {
                this.target_url = target_url;
            }
        }
        
        /// <summary>
        /// Gets or Sets _event
        /// </summary>
        [DataMember(Name="event", EmitDefaultValue=false)]
        public string _event { get; set; }

        /// <summary>
        /// Gets or Sets target_url
        /// </summary>
        [DataMember(Name="target_url", EmitDefaultValue=false)]
        public string target_url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NewWebHookSubscription {\n");
            sb.Append("  _event: ").Append(_event).Append("\n");
            sb.Append("  target_url: ").Append(target_url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NewWebHookSubscription);
        }

        /// <summary>
        /// Returns true if NewWebHookSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of NewWebHookSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NewWebHookSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._event == input._event ||
                    (this._event != null &&
                    this._event.Equals(input._event))
                ) && 
                (
                    this.target_url == input.target_url ||
                    (this.target_url != null &&
                    this.target_url.Equals(input.target_url))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._event != null)
                    hashCode = hashCode * 59 + this._event.GetHashCode();
                if (this.target_url != null)
                    hashCode = hashCode * 59 + this.target_url.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
