/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Product
    /// </summary>
    [DataContract]
    public partial class Product :  IEquatable<Product>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        /// <param name="ID">ID.</param>
        /// <param name="Code">Code.</param>
        /// <param name="Title">Title.</param>
        /// <param name="Description">Description.</param>
        /// <param name="CreationDate">CreationDate.</param>
        /// <param name="Cost">Cost.</param>
        /// <param name="SKU">SKU.</param>
        /// <param name="Comments">Comments.</param>
        /// <param name="CostType">CostType.</param>
        /// <param name="Category1ID">Category1ID.</param>
        /// <param name="Category2ID">Category2ID.</param>
        /// <param name="Category3ID">Category3ID.</param>
        /// <param name="CurrentInventory">CurrentInventory.</param>
        /// <param name="ChargeVAT">ChargeVAT.</param>
        /// <param name="Number">Number.</param>
        /// <param name="PricingType">PricingType.</param>
        /// <param name="PricingTypeText">PricingTypeText.</param>
        /// <param name="Unit">Unit.</param>
        /// <param name="CurrencyID">CurrencyID.</param>
        /// <param name="CurrencyCode">CurrencyCode.</param>
        /// <param name="PurchaseType">PurchaseType.</param>
        /// <param name="IEPSRate">IEPSRate.</param>
        /// <param name="Type">Type.</param>
        /// <param name="ProductionAuto">ProductionAuto.</param>
        public Product(Guid? ID = default(Guid?), string Code = default(string), string Title = default(string), string Description = default(string), DateTime? CreationDate = default(DateTime?), double? Cost = default(double?), string SKU = default(string), string Comments = default(string), int? CostType = default(int?), Guid? Category1ID = default(Guid?), Guid? Category2ID = default(Guid?), Guid? Category3ID = default(Guid?), double? CurrentInventory = default(double?), bool? ChargeVAT = default(bool?), int? Number = default(int?), int? PricingType = default(int?), string PricingTypeText = default(string), string Unit = default(string), Guid? CurrencyID = default(Guid?), string CurrencyCode = default(string), int? PurchaseType = default(int?), double? IEPSRate = default(double?), int? Type = default(int?), bool? ProductionAuto = default(bool?))
        {
            this.ID = ID;
            this.Code = Code;
            this.Title = Title;
            this.Description = Description;
            this.CreationDate = CreationDate;
            this.Cost = Cost;
            this.SKU = SKU;
            this.Comments = Comments;
            this.CostType = CostType;
            this.Category1ID = Category1ID;
            this.Category2ID = Category2ID;
            this.Category3ID = Category3ID;
            this.CurrentInventory = CurrentInventory;
            this.ChargeVAT = ChargeVAT;
            this.Number = Number;
            this.PricingType = PricingType;
            this.PricingTypeText = PricingTypeText;
            this.Unit = Unit;
            this.CurrencyID = CurrencyID;
            this.CurrencyCode = CurrencyCode;
            this.PurchaseType = PurchaseType;
            this.IEPSRate = IEPSRate;
            this.Type = Type;
            this.ProductionAuto = ProductionAuto;
        }
        
        /// <summary>
        /// Gets or Sets ID
        /// </summary>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public Guid? ID { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="Code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="Title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets CreationDate
        /// </summary>
        [DataMember(Name="CreationDate", EmitDefaultValue=false)]
        public DateTime? CreationDate { get; set; }

        /// <summary>
        /// Gets or Sets Cost
        /// </summary>
        [DataMember(Name="Cost", EmitDefaultValue=false)]
        public double? Cost { get; set; }

        /// <summary>
        /// Gets or Sets SKU
        /// </summary>
        [DataMember(Name="SKU", EmitDefaultValue=false)]
        public string SKU { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="Comments", EmitDefaultValue=false)]
        public string Comments { get; set; }

        /// <summary>
        /// Gets or Sets CostType
        /// </summary>
        [DataMember(Name="CostType", EmitDefaultValue=false)]
        public int? CostType { get; set; }

        /// <summary>
        /// Gets or Sets CostTypeText
        /// </summary>
        [DataMember(Name="CostTypeText", EmitDefaultValue=false)]
        public string CostTypeText { get; private set; }

        /// <summary>
        /// Gets or Sets Category1ID
        /// </summary>
        [DataMember(Name="Category1ID", EmitDefaultValue=false)]
        public Guid? Category1ID { get; set; }

        /// <summary>
        /// Gets or Sets Category2ID
        /// </summary>
        [DataMember(Name="Category2ID", EmitDefaultValue=false)]
        public Guid? Category2ID { get; set; }

        /// <summary>
        /// Gets or Sets Category3ID
        /// </summary>
        [DataMember(Name="Category3ID", EmitDefaultValue=false)]
        public Guid? Category3ID { get; set; }

        /// <summary>
        /// Gets or Sets CurrentInventory
        /// </summary>
        [DataMember(Name="CurrentInventory", EmitDefaultValue=false)]
        public double? CurrentInventory { get; set; }

        /// <summary>
        /// Gets or Sets ChargeVAT
        /// </summary>
        [DataMember(Name="ChargeVAT", EmitDefaultValue=false)]
        public bool? ChargeVAT { get; set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name="Number", EmitDefaultValue=false)]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or Sets PricingType
        /// </summary>
        [DataMember(Name="PricingType", EmitDefaultValue=false)]
        public int? PricingType { get; set; }

        /// <summary>
        /// Gets or Sets PricingTypeText
        /// </summary>
        [DataMember(Name="PricingTypeText", EmitDefaultValue=false)]
        public string PricingTypeText { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name="Unit", EmitDefaultValue=false)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyID
        /// </summary>
        [DataMember(Name="CurrencyID", EmitDefaultValue=false)]
        public Guid? CurrencyID { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyCode
        /// </summary>
        [DataMember(Name="CurrencyCode", EmitDefaultValue=false)]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseType
        /// </summary>
        [DataMember(Name="PurchaseType", EmitDefaultValue=false)]
        public int? PurchaseType { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseTypeText
        /// </summary>
        [DataMember(Name="PurchaseTypeText", EmitDefaultValue=false)]
        public string PurchaseTypeText { get; private set; }

        /// <summary>
        /// Gets or Sets IEPSRate
        /// </summary>
        [DataMember(Name="IEPSRate", EmitDefaultValue=false)]
        public double? IEPSRate { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="Type", EmitDefaultValue=false)]
        public int? Type { get; set; }

        /// <summary>
        /// Gets or Sets TypeText
        /// </summary>
        [DataMember(Name="TypeText", EmitDefaultValue=false)]
        public string TypeText { get; private set; }

        /// <summary>
        /// Gets or Sets ProductionAuto
        /// </summary>
        [DataMember(Name="ProductionAuto", EmitDefaultValue=false)]
        public bool? ProductionAuto { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Product {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CreationDate: ").Append(CreationDate).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  SKU: ").Append(SKU).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  CostType: ").Append(CostType).Append("\n");
            sb.Append("  CostTypeText: ").Append(CostTypeText).Append("\n");
            sb.Append("  Category1ID: ").Append(Category1ID).Append("\n");
            sb.Append("  Category2ID: ").Append(Category2ID).Append("\n");
            sb.Append("  Category3ID: ").Append(Category3ID).Append("\n");
            sb.Append("  CurrentInventory: ").Append(CurrentInventory).Append("\n");
            sb.Append("  ChargeVAT: ").Append(ChargeVAT).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PricingType: ").Append(PricingType).Append("\n");
            sb.Append("  PricingTypeText: ").Append(PricingTypeText).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  CurrencyID: ").Append(CurrencyID).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  PurchaseType: ").Append(PurchaseType).Append("\n");
            sb.Append("  PurchaseTypeText: ").Append(PurchaseTypeText).Append("\n");
            sb.Append("  IEPSRate: ").Append(IEPSRate).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TypeText: ").Append(TypeText).Append("\n");
            sb.Append("  ProductionAuto: ").Append(ProductionAuto).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Product);
        }

        /// <summary>
        /// Returns true if Product instances are equal
        /// </summary>
        /// <param name="input">Instance of Product to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Product input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ID == input.ID ||
                    (this.ID != null &&
                    this.ID.Equals(input.ID))
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.CreationDate == input.CreationDate ||
                    (this.CreationDate != null &&
                    this.CreationDate.Equals(input.CreationDate))
                ) && 
                (
                    this.Cost == input.Cost ||
                    (this.Cost != null &&
                    this.Cost.Equals(input.Cost))
                ) && 
                (
                    this.SKU == input.SKU ||
                    (this.SKU != null &&
                    this.SKU.Equals(input.SKU))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.CostType == input.CostType ||
                    (this.CostType != null &&
                    this.CostType.Equals(input.CostType))
                ) && 
                (
                    this.CostTypeText == input.CostTypeText ||
                    (this.CostTypeText != null &&
                    this.CostTypeText.Equals(input.CostTypeText))
                ) && 
                (
                    this.Category1ID == input.Category1ID ||
                    (this.Category1ID != null &&
                    this.Category1ID.Equals(input.Category1ID))
                ) && 
                (
                    this.Category2ID == input.Category2ID ||
                    (this.Category2ID != null &&
                    this.Category2ID.Equals(input.Category2ID))
                ) && 
                (
                    this.Category3ID == input.Category3ID ||
                    (this.Category3ID != null &&
                    this.Category3ID.Equals(input.Category3ID))
                ) && 
                (
                    this.CurrentInventory == input.CurrentInventory ||
                    (this.CurrentInventory != null &&
                    this.CurrentInventory.Equals(input.CurrentInventory))
                ) && 
                (
                    this.ChargeVAT == input.ChargeVAT ||
                    (this.ChargeVAT != null &&
                    this.ChargeVAT.Equals(input.ChargeVAT))
                ) && 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.PricingType == input.PricingType ||
                    (this.PricingType != null &&
                    this.PricingType.Equals(input.PricingType))
                ) && 
                (
                    this.PricingTypeText == input.PricingTypeText ||
                    (this.PricingTypeText != null &&
                    this.PricingTypeText.Equals(input.PricingTypeText))
                ) && 
                (
                    this.Unit == input.Unit ||
                    (this.Unit != null &&
                    this.Unit.Equals(input.Unit))
                ) && 
                (
                    this.CurrencyID == input.CurrencyID ||
                    (this.CurrencyID != null &&
                    this.CurrencyID.Equals(input.CurrencyID))
                ) && 
                (
                    this.CurrencyCode == input.CurrencyCode ||
                    (this.CurrencyCode != null &&
                    this.CurrencyCode.Equals(input.CurrencyCode))
                ) && 
                (
                    this.PurchaseType == input.PurchaseType ||
                    (this.PurchaseType != null &&
                    this.PurchaseType.Equals(input.PurchaseType))
                ) && 
                (
                    this.PurchaseTypeText == input.PurchaseTypeText ||
                    (this.PurchaseTypeText != null &&
                    this.PurchaseTypeText.Equals(input.PurchaseTypeText))
                ) && 
                (
                    this.IEPSRate == input.IEPSRate ||
                    (this.IEPSRate != null &&
                    this.IEPSRate.Equals(input.IEPSRate))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.TypeText == input.TypeText ||
                    (this.TypeText != null &&
                    this.TypeText.Equals(input.TypeText))
                ) && 
                (
                    this.ProductionAuto == input.ProductionAuto ||
                    (this.ProductionAuto != null &&
                    this.ProductionAuto.Equals(input.ProductionAuto))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ID != null)
                    hashCode = hashCode * 59 + this.ID.GetHashCode();
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.CreationDate != null)
                    hashCode = hashCode * 59 + this.CreationDate.GetHashCode();
                if (this.Cost != null)
                    hashCode = hashCode * 59 + this.Cost.GetHashCode();
                if (this.SKU != null)
                    hashCode = hashCode * 59 + this.SKU.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.CostType != null)
                    hashCode = hashCode * 59 + this.CostType.GetHashCode();
                if (this.CostTypeText != null)
                    hashCode = hashCode * 59 + this.CostTypeText.GetHashCode();
                if (this.Category1ID != null)
                    hashCode = hashCode * 59 + this.Category1ID.GetHashCode();
                if (this.Category2ID != null)
                    hashCode = hashCode * 59 + this.Category2ID.GetHashCode();
                if (this.Category3ID != null)
                    hashCode = hashCode * 59 + this.Category3ID.GetHashCode();
                if (this.CurrentInventory != null)
                    hashCode = hashCode * 59 + this.CurrentInventory.GetHashCode();
                if (this.ChargeVAT != null)
                    hashCode = hashCode * 59 + this.ChargeVAT.GetHashCode();
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.PricingType != null)
                    hashCode = hashCode * 59 + this.PricingType.GetHashCode();
                if (this.PricingTypeText != null)
                    hashCode = hashCode * 59 + this.PricingTypeText.GetHashCode();
                if (this.Unit != null)
                    hashCode = hashCode * 59 + this.Unit.GetHashCode();
                if (this.CurrencyID != null)
                    hashCode = hashCode * 59 + this.CurrencyID.GetHashCode();
                if (this.CurrencyCode != null)
                    hashCode = hashCode * 59 + this.CurrencyCode.GetHashCode();
                if (this.PurchaseType != null)
                    hashCode = hashCode * 59 + this.PurchaseType.GetHashCode();
                if (this.PurchaseTypeText != null)
                    hashCode = hashCode * 59 + this.PurchaseTypeText.GetHashCode();
                if (this.IEPSRate != null)
                    hashCode = hashCode * 59 + this.IEPSRate.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.TypeText != null)
                    hashCode = hashCode * 59 + this.TypeText.GetHashCode();
                if (this.ProductionAuto != null)
                    hashCode = hashCode * 59 + this.ProductionAuto.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
