/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WebHookSubscription
    /// </summary>
    [DataContract]
    public partial class WebHookSubscription :  IEquatable<WebHookSubscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebHookSubscription" /> class.
        /// </summary>
        /// <param name="ID">ID.</param>
        /// <param name="EventID">EventID.</param>
        /// <param name="TargetURL">TargetURL.</param>
        /// <param name="EventName">EventName.</param>
        public WebHookSubscription(Guid? ID = default(Guid?), string EventID = default(string), string TargetURL = default(string), string EventName = default(string))
        {
            this.ID = ID;
            this.EventID = EventID;
            this.TargetURL = TargetURL;
            this.EventName = EventName;
        }
        
        /// <summary>
        /// Gets or Sets ID
        /// </summary>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public Guid? ID { get; set; }

        /// <summary>
        /// Gets or Sets EventID
        /// </summary>
        [DataMember(Name="EventID", EmitDefaultValue=false)]
        public string EventID { get; set; }

        /// <summary>
        /// Gets or Sets TargetURL
        /// </summary>
        [DataMember(Name="TargetURL", EmitDefaultValue=false)]
        public string TargetURL { get; set; }

        /// <summary>
        /// Gets or Sets EventName
        /// </summary>
        [DataMember(Name="EventName", EmitDefaultValue=false)]
        public string EventName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WebHookSubscription {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  EventID: ").Append(EventID).Append("\n");
            sb.Append("  TargetURL: ").Append(TargetURL).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WebHookSubscription);
        }

        /// <summary>
        /// Returns true if WebHookSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of WebHookSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WebHookSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ID == input.ID ||
                    (this.ID != null &&
                    this.ID.Equals(input.ID))
                ) && 
                (
                    this.EventID == input.EventID ||
                    (this.EventID != null &&
                    this.EventID.Equals(input.EventID))
                ) && 
                (
                    this.TargetURL == input.TargetURL ||
                    (this.TargetURL != null &&
                    this.TargetURL.Equals(input.TargetURL))
                ) && 
                (
                    this.EventName == input.EventName ||
                    (this.EventName != null &&
                    this.EventName.Equals(input.EventName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ID != null)
                    hashCode = hashCode * 59 + this.ID.GetHashCode();
                if (this.EventID != null)
                    hashCode = hashCode * 59 + this.EventID.GetHashCode();
                if (this.TargetURL != null)
                    hashCode = hashCode * 59 + this.TargetURL.GetHashCode();
                if (this.EventName != null)
                    hashCode = hashCode * 59 + this.EventName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
