/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FilterQueryOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterQueryOptionTests
    {
        // TODO uncomment below to declare an instance variable for FilterQueryOption
        //private FilterQueryOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilterQueryOption
            //instance = new FilterQueryOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilterQueryOption
        /// </summary>
        [Test]
        public void FilterQueryOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilterQueryOption
            //Assert.IsInstanceOfType<FilterQueryOption> (instance, "variable 'instance' is a FilterQueryOption");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Validator'
        /// </summary>
        [Test]
        public void ValidatorTest()
        {
            // TODO unit test for the property 'Validator'
        }
        /// <summary>
        /// Test the property 'FilterClause'
        /// </summary>
        [Test]
        public void FilterClauseTest()
        {
            // TODO unit test for the property 'FilterClause'
        }
        /// <summary>
        /// Test the property 'RawValue'
        /// </summary>
        [Test]
        public void RawValueTest()
        {
            // TODO unit test for the property 'RawValue'
        }

    }

}
