/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IEdmModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IEdmModelTests
    {
        // TODO uncomment below to declare an instance variable for IEdmModel
        //private IEdmModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IEdmModel
            //instance = new IEdmModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IEdmModel
        /// </summary>
        [Test]
        public void IEdmModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IEdmModel
            //Assert.IsInstanceOfType<IEdmModel> (instance, "variable 'instance' is a IEdmModel");
        }


        /// <summary>
        /// Test the property 'SchemaElements'
        /// </summary>
        [Test]
        public void SchemaElementsTest()
        {
            // TODO unit test for the property 'SchemaElements'
        }
        /// <summary>
        /// Test the property 'VocabularyAnnotations'
        /// </summary>
        [Test]
        public void VocabularyAnnotationsTest()
        {
            // TODO unit test for the property 'VocabularyAnnotations'
        }
        /// <summary>
        /// Test the property 'ReferencedModels'
        /// </summary>
        [Test]
        public void ReferencedModelsTest()
        {
            // TODO unit test for the property 'ReferencedModels'
        }
        /// <summary>
        /// Test the property 'DirectValueAnnotationsManager'
        /// </summary>
        [Test]
        public void DirectValueAnnotationsManagerTest()
        {
            // TODO unit test for the property 'DirectValueAnnotationsManager'
        }

    }

}
