/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Inventory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InventoryTests
    {
        // TODO uncomment below to declare an instance variable for Inventory
        //private Inventory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Inventory
            //instance = new Inventory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Inventory
        /// </summary>
        [Test]
        public void InventoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Inventory
            //Assert.IsInstanceOfType<Inventory> (instance, "variable 'instance' is a Inventory");
        }


        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'ClientOrdered'
        /// </summary>
        [Test]
        public void ClientOrderedTest()
        {
            // TODO unit test for the property 'ClientOrdered'
        }
        /// <summary>
        /// Test the property 'CurrentInventory'
        /// </summary>
        [Test]
        public void CurrentInventoryTest()
        {
            // TODO unit test for the property 'CurrentInventory'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'ProvidedOrdered'
        /// </summary>
        [Test]
        public void ProvidedOrderedTest()
        {
            // TODO unit test for the property 'ProvidedOrdered'
        }
        /// <summary>
        /// Test the property 'SKU'
        /// </summary>
        [Test]
        public void SKUTest()
        {
            // TODO unit test for the property 'SKU'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
