/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InvoiceDetailsService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvoiceDetailsServiceTests
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailsService
        //private InvoiceDetailsService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvoiceDetailsService
            //instance = new InvoiceDetailsService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvoiceDetailsService
        /// </summary>
        [Test]
        public void InvoiceDetailsServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvoiceDetailsService
            //Assert.IsInstanceOfType<InvoiceDetailsService> (instance, "variable 'instance' is a InvoiceDetailsService");
        }


        /// <summary>
        /// Test the property 'IndexNumber'
        /// </summary>
        [Test]
        public void IndexNumberTest()
        {
            // TODO unit test for the property 'IndexNumber'
        }
        /// <summary>
        /// Test the property 'ServiceID'
        /// </summary>
        [Test]
        public void ServiceIDTest()
        {
            // TODO unit test for the property 'ServiceID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Test]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'VATRate'
        /// </summary>
        [Test]
        public void VATRateTest()
        {
            // TODO unit test for the property 'VATRate'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }

    }

}
