/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
<<<<<<< HEAD
 * OpenAPI spec version: v1
=======
 * OpenAPI spec version: v1.2
>>>>>>> 00a0f02ad3caf59a4284f6cc77ac538a3fc20070
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InvoiceListItemPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvoiceListItemPageTests
    {
        // TODO uncomment below to declare an instance variable for InvoiceListItemPage
        //private InvoiceListItemPage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvoiceListItemPage
            //instance = new InvoiceListItemPage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvoiceListItemPage
        /// </summary>
        [Test]
        public void InvoiceListItemPageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvoiceListItemPage
            //Assert.IsInstanceOfType<InvoiceListItemPage> (instance, "variable 'instance' is a InvoiceListItemPage");
        }


        /// <summary>
<<<<<<< HEAD
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'NextLink'
        /// </summary>
        [Test]
        public void NextLinkTest()
        {
            // TODO unit test for the property 'NextLink'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
=======
        /// Test the property 'value'
        /// </summary>
        [Test]
        public void valueTest()
        {
            // TODO unit test for the property 'value'
        }
        /// <summary>
        /// Test the property 'nextLink'
        /// </summary>
        [Test]
        public void nextLinkTest()
        {
            // TODO unit test for the property 'nextLink'
        }
        /// <summary>
        /// Test the property 'count'
        /// </summary>
        [Test]
        public void countTest()
        {
            // TODO unit test for the property 'count'
>>>>>>> 00a0f02ad3caf59a4284f6cc77ac538a3fc20070
        }

    }

}
