/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewCreditNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewCreditNoteTests
    {
        // TODO uncomment below to declare an instance variable for NewCreditNote
        //private NewCreditNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewCreditNote
            //instance = new NewCreditNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewCreditNote
        /// </summary>
        [Test]
        public void NewCreditNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewCreditNote
            //Assert.IsInstanceOfType<NewCreditNote> (instance, "variable 'instance' is a NewCreditNote");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Concept'
        /// </summary>
        [Test]
        public void ConceptTest()
        {
            // TODO unit test for the property 'Concept'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'CreditNotesItems'
        /// </summary>
        [Test]
        public void CreditNotesItemsTest()
        {
            // TODO unit test for the property 'CreditNotesItems'
        }
        /// <summary>
        /// Test the property 'IEPSAmount'
        /// </summary>
        [Test]
        public void IEPSAmountTest()
        {
            // TODO unit test for the property 'IEPSAmount'
        }
        /// <summary>
        /// Test the property 'InvoiceID'
        /// </summary>
        [Test]
        public void InvoiceIDTest()
        {
            // TODO unit test for the property 'InvoiceID'
        }
        /// <summary>
        /// Test the property 'ISRRet'
        /// </summary>
        [Test]
        public void ISRRetTest()
        {
            // TODO unit test for the property 'ISRRet'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PaymentTerms'
        /// </summary>
        [Test]
        public void PaymentTermsTest()
        {
            // TODO unit test for the property 'PaymentTerms'
        }
        /// <summary>
        /// Test the property 'SeriesID'
        /// </summary>
        [Test]
        public void SeriesIDTest()
        {
            // TODO unit test for the property 'SeriesID'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'VAT'
        /// </summary>
        [Test]
        public void VATTest()
        {
            // TODO unit test for the property 'VAT'
        }
        /// <summary>
        /// Test the property 'VATRet'
        /// </summary>
        [Test]
        public void VATRetTest()
        {
            // TODO unit test for the property 'VATRet'
        }

    }

}
