/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewOrderTests
    {
        // TODO uncomment below to declare an instance variable for NewOrder
        //private NewOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewOrder
            //instance = new NewOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewOrder
        /// </summary>
        [Test]
        public void NewOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewOrder
            //Assert.IsInstanceOfType<NewOrder> (instance, "variable 'instance' is a NewOrder");
        }


        /// <summary>
        /// Test the property 'AddressID'
        /// </summary>
        [Test]
        public void AddressIDTest()
        {
            // TODO unit test for the property 'AddressID'
        }
        /// <summary>
        /// Test the property 'ClientID'
        /// </summary>
        [Test]
        public void ClientIDTest()
        {
            // TODO unit test for the property 'ClientID'
        }
        /// <summary>
        /// Test the property 'CurrencyID'
        /// </summary>
        [Test]
        public void CurrencyIDTest()
        {
            // TODO unit test for the property 'CurrencyID'
        }
        /// <summary>
        /// Test the property 'LocationID'
        /// </summary>
        [Test]
        public void LocationIDTest()
        {
            // TODO unit test for the property 'LocationID'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Test]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'PriceListID'
        /// </summary>
        [Test]
        public void PriceListIDTest()
        {
            // TODO unit test for the property 'PriceListID'
        }
        /// <summary>
        /// Test the property 'WarehouseID'
        /// </summary>
        [Test]
        public void WarehouseIDTest()
        {
            // TODO unit test for the property 'WarehouseID'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [Test]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }
        /// <summary>
        /// Test the property 'DiscountType'
        /// </summary>
        [Test]
        public void DiscountTypeTest()
        {
            // TODO unit test for the property 'DiscountType'
        }
        /// <summary>
        /// Test the property 'DocNumberID'
        /// </summary>
        [Test]
        public void DocNumberIDTest()
        {
            // TODO unit test for the property 'DocNumberID'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'ISRRate'
        /// </summary>
        [Test]
        public void ISRRateTest()
        {
            // TODO unit test for the property 'ISRRate'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Test]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'VATRate'
        /// </summary>
        [Test]
        public void VATRateTest()
        {
            // TODO unit test for the property 'VATRate'
        }
        /// <summary>
        /// Test the property 'VATRetRate'
        /// </summary>
        [Test]
        public void VATRetRateTest()
        {
            // TODO unit test for the property 'VATRetRate'
        }
        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Test]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Test]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

    }

}
