/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewServiceTests
    {
        // TODO uncomment below to declare an instance variable for NewService
        //private NewService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewService
            //instance = new NewService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewService
        /// </summary>
        [Test]
        public void NewServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewService
            //Assert.IsInstanceOfType<NewService> (instance, "variable 'instance' is a NewService");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'CurrencyID'
        /// </summary>
        [Test]
        public void CurrencyIDTest()
        {
            // TODO unit test for the property 'CurrencyID'
        }
        /// <summary>
        /// Test the property 'SATCompanyAccountID'
        /// </summary>
        [Test]
        public void SATCompanyAccountIDTest()
        {
            // TODO unit test for the property 'SATCompanyAccountID'
        }
        /// <summary>
        /// Test the property 'MeasurementUnit'
        /// </summary>
        [Test]
        public void MeasurementUnitTest()
        {
            // TODO unit test for the property 'MeasurementUnit'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Category1ID'
        /// </summary>
        [Test]
        public void Category1IDTest()
        {
            // TODO unit test for the property 'Category1ID'
        }
        /// <summary>
        /// Test the property 'Category2ID'
        /// </summary>
        [Test]
        public void Category2IDTest()
        {
            // TODO unit test for the property 'Category2ID'
        }
        /// <summary>
        /// Test the property 'Category3ID'
        /// </summary>
        [Test]
        public void Category3IDTest()
        {
            // TODO unit test for the property 'Category3ID'
        }
        /// <summary>
        /// Test the property 'VariableConcept'
        /// </summary>
        [Test]
        public void VariableConceptTest()
        {
            // TODO unit test for the property 'VariableConcept'
        }
        /// <summary>
        /// Test the property 'ChargeVAT'
        /// </summary>
        [Test]
        public void ChargeVATTest()
        {
            // TODO unit test for the property 'ChargeVAT'
        }

    }

}
