/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ODataQueryOptionsFlatAccountingJournal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ODataQueryOptionsFlatAccountingJournalTests
    {
        // TODO uncomment below to declare an instance variable for ODataQueryOptionsFlatAccountingJournal
        //private ODataQueryOptionsFlatAccountingJournal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ODataQueryOptionsFlatAccountingJournal
            //instance = new ODataQueryOptionsFlatAccountingJournal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ODataQueryOptionsFlatAccountingJournal
        /// </summary>
        [Test]
        public void ODataQueryOptionsFlatAccountingJournalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ODataQueryOptionsFlatAccountingJournal
            //Assert.IsInstanceOfType<ODataQueryOptionsFlatAccountingJournal> (instance, "variable 'instance' is a ODataQueryOptionsFlatAccountingJournal");
        }


        /// <summary>
        /// Test the property 'IfMatch'
        /// </summary>
        [Test]
        public void IfMatchTest()
        {
            // TODO unit test for the property 'IfMatch'
        }
        /// <summary>
        /// Test the property 'IfNoneMatch'
        /// </summary>
        [Test]
        public void IfNoneMatchTest()
        {
            // TODO unit test for the property 'IfNoneMatch'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'RawValues'
        /// </summary>
        [Test]
        public void RawValuesTest()
        {
            // TODO unit test for the property 'RawValues'
        }
        /// <summary>
        /// Test the property 'SelectExpand'
        /// </summary>
        [Test]
        public void SelectExpandTest()
        {
            // TODO unit test for the property 'SelectExpand'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Test]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Test]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }
        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Test]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }
        /// <summary>
        /// Test the property 'InlineCount'
        /// </summary>
        [Test]
        public void InlineCountTest()
        {
            // TODO unit test for the property 'InlineCount'
        }
        /// <summary>
        /// Test the property 'Validator'
        /// </summary>
        [Test]
        public void ValidatorTest()
        {
            // TODO unit test for the property 'Validator'
        }

    }

}
