/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderByQueryOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderByQueryOptionTests
    {
        // TODO uncomment below to declare an instance variable for OrderByQueryOption
        //private OrderByQueryOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderByQueryOption
            //instance = new OrderByQueryOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderByQueryOption
        /// </summary>
        [Test]
        public void OrderByQueryOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderByQueryOption
            //Assert.IsInstanceOfType<OrderByQueryOption> (instance, "variable 'instance' is a OrderByQueryOption");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'OrderByNodes'
        /// </summary>
        [Test]
        public void OrderByNodesTest()
        {
            // TODO unit test for the property 'OrderByNodes'
        }
        /// <summary>
        /// Test the property 'RawValue'
        /// </summary>
        [Test]
        public void RawValueTest()
        {
            // TODO unit test for the property 'RawValue'
        }
        /// <summary>
        /// Test the property 'Validator'
        /// </summary>
        [Test]
        public void ValidatorTest()
        {
            // TODO unit test for the property 'Validator'
        }
        /// <summary>
        /// Test the property 'OrderByClause'
        /// </summary>
        [Test]
        public void OrderByClauseTest()
        {
            // TODO unit test for the property 'OrderByClause'
        }

    }

}
