/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderDetailsTests
    {
        // TODO uncomment below to declare an instance variable for OrderDetails
        //private OrderDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderDetails
            //instance = new OrderDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderDetails
        /// </summary>
        [Test]
        public void OrderDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderDetails
            //Assert.IsInstanceOfType<OrderDetails> (instance, "variable 'instance' is a OrderDetails");
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'ClientID'
        /// </summary>
        [Test]
        public void ClientIDTest()
        {
            // TODO unit test for the property 'ClientID'
        }
        /// <summary>
        /// Test the property 'ClientName'
        /// </summary>
        [Test]
        public void ClientNameTest()
        {
            // TODO unit test for the property 'ClientName'
        }
        /// <summary>
        /// Test the property 'PriceListName'
        /// </summary>
        [Test]
        public void PriceListNameTest()
        {
            // TODO unit test for the property 'PriceListName'
        }
        /// <summary>
        /// Test the property 'PriceListID'
        /// </summary>
        [Test]
        public void PriceListIDTest()
        {
            // TODO unit test for the property 'PriceListID'
        }
        /// <summary>
        /// Test the property 'LocationName'
        /// </summary>
        [Test]
        public void LocationNameTest()
        {
            // TODO unit test for the property 'LocationName'
        }
        /// <summary>
        /// Test the property 'LocationID'
        /// </summary>
        [Test]
        public void LocationIDTest()
        {
            // TODO unit test for the property 'LocationID'
        }
        /// <summary>
        /// Test the property 'WarehouseID'
        /// </summary>
        [Test]
        public void WarehouseIDTest()
        {
            // TODO unit test for the property 'WarehouseID'
        }
        /// <summary>
        /// Test the property 'WarehouseName'
        /// </summary>
        [Test]
        public void WarehouseNameTest()
        {
            // TODO unit test for the property 'WarehouseName'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Test]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ClientContact'
        /// </summary>
        [Test]
        public void ClientContactTest()
        {
            // TODO unit test for the property 'ClientContact'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'EmployeeName'
        /// </summary>
        [Test]
        public void EmployeeNameTest()
        {
            // TODO unit test for the property 'EmployeeName'
        }
        /// <summary>
        /// Test the property 'EmployeeID'
        /// </summary>
        [Test]
        public void EmployeeIDTest()
        {
            // TODO unit test for the property 'EmployeeID'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Test]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CurrencyName'
        /// </summary>
        [Test]
        public void CurrencyNameTest()
        {
            // TODO unit test for the property 'CurrencyName'
        }
        /// <summary>
        /// Test the property 'CurrencyID'
        /// </summary>
        [Test]
        public void CurrencyIDTest()
        {
            // TODO unit test for the property 'CurrencyID'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'RFC'
        /// </summary>
        [Test]
        public void RFCTest()
        {
            // TODO unit test for the property 'RFC'
        }
        /// <summary>
        /// Test the property 'ServiceSubtotal'
        /// </summary>
        [Test]
        public void ServiceSubtotalTest()
        {
            // TODO unit test for the property 'ServiceSubtotal'
        }
        /// <summary>
        /// Test the property 'ProductSubtotal'
        /// </summary>
        [Test]
        public void ProductSubtotalTest()
        {
            // TODO unit test for the property 'ProductSubtotal'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'VATRate'
        /// </summary>
        [Test]
        public void VATRateTest()
        {
            // TODO unit test for the property 'VATRate'
        }
        /// <summary>
        /// Test the property 'VAT'
        /// </summary>
        [Test]
        public void VATTest()
        {
            // TODO unit test for the property 'VAT'
        }
        /// <summary>
        /// Test the property 'DiscountType'
        /// </summary>
        [Test]
        public void DiscountTypeTest()
        {
            // TODO unit test for the property 'DiscountType'
        }
        /// <summary>
        /// Test the property 'IEPS'
        /// </summary>
        [Test]
        public void IEPSTest()
        {
            // TODO unit test for the property 'IEPS'
        }
        /// <summary>
        /// Test the property 'IEPSRATE'
        /// </summary>
        [Test]
        public void IEPSRATETest()
        {
            // TODO unit test for the property 'IEPSRATE'
        }
        /// <summary>
        /// Test the property 'ISRRet'
        /// </summary>
        [Test]
        public void ISRRetTest()
        {
            // TODO unit test for the property 'ISRRet'
        }
        /// <summary>
        /// Test the property 'ISRRetRate'
        /// </summary>
        [Test]
        public void ISRRetRateTest()
        {
            // TODO unit test for the property 'ISRRetRate'
        }
        /// <summary>
        /// Test the property 'VatRet'
        /// </summary>
        [Test]
        public void VatRetTest()
        {
            // TODO unit test for the property 'VatRet'
        }
        /// <summary>
        /// Test the property 'VatRetRate'
        /// </summary>
        [Test]
        public void VatRetRateTest()
        {
            // TODO unit test for the property 'VatRetRate'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Test]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

    }

}
