/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductInventories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductInventoriesTests
    {
        // TODO uncomment below to declare an instance variable for ProductInventories
        //private ProductInventories instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductInventories
            //instance = new ProductInventories();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductInventories
        /// </summary>
        [Test]
        public void ProductInventoriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductInventories
            //Assert.IsInstanceOfType<ProductInventories> (instance, "variable 'instance' is a ProductInventories");
        }


        /// <summary>
        /// Test the property 'WarehouseName'
        /// </summary>
        [Test]
        public void WarehouseNameTest()
        {
            // TODO unit test for the property 'WarehouseName'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Test]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Test]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }
        /// <summary>
        /// Test the property 'Inventory'
        /// </summary>
        [Test]
        public void InventoryTest()
        {
            // TODO unit test for the property 'Inventory'
        }

    }

}
