/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductTests
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Test]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Product
            //Assert.IsInstanceOfType<Product> (instance, "variable 'instance' is a Product");
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'SKU'
        /// </summary>
        [Test]
        public void SKUTest()
        {
            // TODO unit test for the property 'SKU'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'CostType'
        /// </summary>
        [Test]
        public void CostTypeTest()
        {
            // TODO unit test for the property 'CostType'
        }
        /// <summary>
        /// Test the property 'CostTypeText'
        /// </summary>
        [Test]
        public void CostTypeTextTest()
        {
            // TODO unit test for the property 'CostTypeText'
        }
        /// <summary>
        /// Test the property 'Category1ID'
        /// </summary>
        [Test]
        public void Category1IDTest()
        {
            // TODO unit test for the property 'Category1ID'
        }
        /// <summary>
        /// Test the property 'Category2ID'
        /// </summary>
        [Test]
        public void Category2IDTest()
        {
            // TODO unit test for the property 'Category2ID'
        }
        /// <summary>
        /// Test the property 'Category3ID'
        /// </summary>
        [Test]
        public void Category3IDTest()
        {
            // TODO unit test for the property 'Category3ID'
        }
        /// <summary>
        /// Test the property 'CurrentInventory'
        /// </summary>
        [Test]
        public void CurrentInventoryTest()
        {
            // TODO unit test for the property 'CurrentInventory'
        }
        /// <summary>
        /// Test the property 'ChargeVAT'
        /// </summary>
        [Test]
        public void ChargeVATTest()
        {
            // TODO unit test for the property 'ChargeVAT'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'PricingType'
        /// </summary>
        [Test]
        public void PricingTypeTest()
        {
            // TODO unit test for the property 'PricingType'
        }
        /// <summary>
        /// Test the property 'PricingTypeText'
        /// </summary>
        [Test]
        public void PricingTypeTextTest()
        {
            // TODO unit test for the property 'PricingTypeText'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'CurrencyID'
        /// </summary>
        [Test]
        public void CurrencyIDTest()
        {
            // TODO unit test for the property 'CurrencyID'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'PurchaseType'
        /// </summary>
        [Test]
        public void PurchaseTypeTest()
        {
            // TODO unit test for the property 'PurchaseType'
        }
        /// <summary>
        /// Test the property 'PurchaseTypeText'
        /// </summary>
        [Test]
        public void PurchaseTypeTextTest()
        {
            // TODO unit test for the property 'PurchaseTypeText'
        }
        /// <summary>
        /// Test the property 'IEPSRate'
        /// </summary>
        [Test]
        public void IEPSRateTest()
        {
            // TODO unit test for the property 'IEPSRate'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeText'
        /// </summary>
        [Test]
        public void TypeTextTest()
        {
            // TODO unit test for the property 'TypeText'
        }
        /// <summary>
        /// Test the property 'ProductionAuto'
        /// </summary>
        [Test]
        public void ProductionAutoTest()
        {
            // TODO unit test for the property 'ProductionAuto'
        }

    }

}
