/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SelectExpandQueryOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SelectExpandQueryOptionTests
    {
        // TODO uncomment below to declare an instance variable for SelectExpandQueryOption
        //private SelectExpandQueryOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SelectExpandQueryOption
            //instance = new SelectExpandQueryOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SelectExpandQueryOption
        /// </summary>
        [Test]
        public void SelectExpandQueryOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SelectExpandQueryOption
            //Assert.IsInstanceOfType<SelectExpandQueryOption> (instance, "variable 'instance' is a SelectExpandQueryOption");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'RawSelect'
        /// </summary>
        [Test]
        public void RawSelectTest()
        {
            // TODO unit test for the property 'RawSelect'
        }
        /// <summary>
        /// Test the property 'RawExpand'
        /// </summary>
        [Test]
        public void RawExpandTest()
        {
            // TODO unit test for the property 'RawExpand'
        }
        /// <summary>
        /// Test the property 'Validator'
        /// </summary>
        [Test]
        public void ValidatorTest()
        {
            // TODO unit test for the property 'Validator'
        }
        /// <summary>
        /// Test the property 'SelectExpandClause'
        /// </summary>
        [Test]
        public void SelectExpandClauseTest()
        {
            // TODO unit test for the property 'SelectExpandClause'
        }

    }

}
