/* 
 * Bind ERP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebHookSubscriptionPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebHookSubscriptionPageTests
    {
        // TODO uncomment below to declare an instance variable for WebHookSubscriptionPage
        //private WebHookSubscriptionPage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebHookSubscriptionPage
            //instance = new WebHookSubscriptionPage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHookSubscriptionPage
        /// </summary>
        [Test]
        public void WebHookSubscriptionPageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebHookSubscriptionPage
            //Assert.IsInstanceOfType<WebHookSubscriptionPage> (instance, "variable 'instance' is a WebHookSubscriptionPage");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'NextLink'
        /// </summary>
        [Test]
        public void NextLinkTest()
        {
            // TODO unit test for the property 'NextLink'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

    }

}
